//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAYER()
        {
            this.USERTEAM = new HashSet<USERTEAM>();
            this.USERTEAM1 = new HashSet<USERTEAM>();
            this.USERTEAM2 = new HashSet<USERTEAM>();
            this.USERTEAM3 = new HashSet<USERTEAM>();
            this.USERTEAM4 = new HashSet<USERTEAM>();
            this.USERTEAM5 = new HashSet<USERTEAM>();
            this.USERTEAM6 = new HashSet<USERTEAM>();
            this.USERTEAM7 = new HashSet<USERTEAM>();
            this.USERTEAM8 = new HashSet<USERTEAM>();
            this.USERTEAM9 = new HashSet<USERTEAM>();
            this.USERTEAM10 = new HashSet<USERTEAM>();
            this.USERTEAM11 = new HashSet<USERTEAM>();
            this.USERTEAM12 = new HashSet<USERTEAM>();
            this.USERTEAM13 = new HashSet<USERTEAM>();
            this.USERTEAM14 = new HashSet<USERTEAM>();
        }
    
        public string PLAYER1 { get; set; }
        public string TEAM { get; set; }
        public Nullable<double> AGE { get; set; }
        public Nullable<double> GP { get; set; }
        public Nullable<double> W { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> MIN { get; set; }
        public string PTS { get; set; }
        public Nullable<double> FGM { get; set; }
        public Nullable<double> FGA { get; set; }
        public string FG_ { get; set; }
        public string C3PM { get; set; }
        public string C3PA { get; set; }
        public string C3P_ { get; set; }
        public string FTM { get; set; }
        public string FTA { get; set; }
        public string FT_ { get; set; }
        public Nullable<double> OREB { get; set; }
        public Nullable<double> DREB { get; set; }
        public Nullable<double> REB { get; set; }
        public Nullable<double> AST { get; set; }
        public Nullable<double> TOV { get; set; }
        public Nullable<double> STL { get; set; }
        public Nullable<double> BLK { get; set; }
        public Nullable<double> PF { get; set; }
        public Nullable<double> FP { get; set; }
        public Nullable<double> DD2 { get; set; }
        public Nullable<double> TD3 { get; set; }
        public Nullable<double> C___ { get; set; }
        public Nullable<double> RAT { get; set; }
        public Nullable<double> DIFF { get; set; }
        public Nullable<double> RPMRAT { get; set; }
        public Nullable<double> ORRAT { get; set; }
        public Nullable<double> W_L { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEAM> USERTEAM14 { get; set; }
    }
}
