//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTEAM
    {
        public string User { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Player1 { get; set; }
        public Nullable<int> Player2 { get; set; }
        public Nullable<int> Player3 { get; set; }
        public Nullable<int> Player4 { get; set; }
        public Nullable<int> Player5 { get; set; }
        public Nullable<int> Player6 { get; set; }
        public Nullable<int> Player7 { get; set; }
        public Nullable<int> Player8 { get; set; }
        public Nullable<int> Player9 { get; set; }
        public Nullable<int> Player10 { get; set; }
        public Nullable<int> Player11 { get; set; }
        public Nullable<int> Player12 { get; set; }
        public Nullable<int> Player13 { get; set; }
        public Nullable<int> Player14 { get; set; }
        public Nullable<int> Player15 { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
        public virtual PLAYER PLAYER16 { get; set; }
        public virtual PLAYER PLAYER17 { get; set; }
        public virtual PLAYER PLAYER18 { get; set; }
        public virtual PLAYER PLAYER19 { get; set; }
        public virtual PLAYER PLAYER20 { get; set; }
        public virtual PLAYER PLAYER21 { get; set; }
        public virtual PLAYER PLAYER22 { get; set; }
        public virtual PLAYER PLAYER23 { get; set; }
        public virtual PLAYER PLAYER24 { get; set; }
        public virtual PLAYER PLAYER25 { get; set; }
        public virtual PLAYER PLAYER26 { get; set; }
        public virtual PLAYER PLAYER27 { get; set; }
        public virtual PLAYER PLAYER28 { get; set; }
        public virtual PLAYER PLAYER29 { get; set; }
    }
}
